Division
CodingTrain/TestingTestTest pull request #22
Opened 2018-02-02 17:35 UTC by Christian-Seiler

2018-02-02 17:40 UTC, MatthewBraun commented
Awesome :D

2018-02-08 12:24 UTC, shiffman requested changes

2018-02-08 12:24 UTC, shiffman commented on sketch.test.js
> +const { sum, prod, devide } = require('./sketch');
Looks like there's a spelling error here?

2018-02-08 12:24 UTC, shiffman commented on sketch.test.js
> +  expect(devide(4,2)).toBe(2);
And here too!

2022-05-01 06:37 UTC, closed without merging